sudo: required

language: scala

dist: trusty

env:
  - ANDROID_HOME=$PWD/

jdk:
  - oraclejdk8

before_install:
  - npm install -g cordova
  - cd th-player
  - cordova prepare
  - cd ../

install:
    - wget --quiet --output-document=tools.zip https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
    - unzip -qq tools.zip
    - echo y | tools/bin/sdkmanager "platforms;android-25"
    - echo y | tools/bin/sdkmanager "platform-tools"
    - echo y | tools/bin/sdkmanager "build-tools;25.0.2"
    - echo y | tools/bin/sdkmanager "extras;android;m2repository"
    - echo y | tools/bin/sdkmanager "extras;google;m2repository"

script:
  - ./gradlew

deploy:
  - provider: releases
    api_key: $GITHUB_KEY
    file_glob: true
    file:
      - th-player/platforms/android/build/outputs/apk/debug/*.apk
      - th-server/build/libs/*.jar
    skip_cleanup: true
    on:
      tags: true
      
services:
  - rabbitmq
